---
title: Jekyll Heroku Starter Kit
description: Minimum boilerplate code for setting up and running a Jekyll site on Heroku.
timezone: Africa/Johannesburg
locale: en_ZA
## Set the url to your site below ##
url:
baseurl:
## Enabling Collections for the Site. ##
collections:
  posts:
    title                     : Posts
    output                    : true # Set this to false to prevent from appearing on site.
    permalink                 : /:categories/:title.html
  pages:
    title                     : Pages
    output                    : true
    permalink                 : /:categories/:title.html
## Theme settings ##
theme: jekyll-theme-minimal
logo: https://via.placeholder.com/250x100.png/E8117F/fff?text=Logo+Placeholder
show_downloads: true
google_analytics: UA-100937492-4
## Exclude files from the build ##
exclude:
- '_site'
- '.bundle'
- '.github'
- '.sass-cache'
- 'vendor'
- '_config.yml'
- '.gitignore'
- 'CHANGELOG.md'
- 'CODE_OF_CONDUCT.md'
- 'config.ru'
- 'CONTRIBUTING.md'
- 'Gemfile'
- 'Gemfile.lock'
- 'LICENSE'
- 'Procfile'
- 'Rakefile'
- 'README.md'
- 'starter-kit.code-workspace'
- 'static.json'
## Configure and setup plugins for the site. ##
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate-v2
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-redirect-from
## All the Settings for the @jekyll-seo-tag ##
# Your twitter details
twitter:
  username: justinhartman
  card: summary
# Facebook App ID. You need to create an app at:
# https://developers.facebook.com/apps
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234
# Links to other social profiles or websites that relate to you.
social:
  name: Justin Hartman
  links:
    - https://twitter.com/justinhartman
    - https://www.facebook.com/justin.hartman.me
    - https://www.linkedin.com/in/justinhartman
    - https://plus.google.com/+iamjustinhartman
    - https://github.com/justinhartman
# When you verify with either of the Webmaster Tools below, enter the
# verification key below.
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
# Setting a default image:
# Settings to provide a default Twitter Card or OGP image to all of your 
# posts and pages.
defaults:
  - scope:
      path: ""
    values:
      image: /assets/default-card.png # change this to a Generic image.
---
